// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubgkzcwyupfpcqqyeutc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViZ2t6Y3d5dXBmcGNxcXlldXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzAyMzQsImV4cCI6MjA3MzEwNjIzNH0.q2S_rkG2HmiaFju-lBAdYA-kRcoPqNIf5rVmIMLt_fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});